apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cloud-storage-app
  template:
    metadata:
      labels:
        app: cloud-storage-app
    spec:
      containers:
      - name: cloud-storage-app
        image: cloud-storage-app
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-app-service
spec:
  selector:
    app: cloud-storage-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer