version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    links:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_URI=mongodb+srv://storage:Abhey123@cluster0.i4dedvi.mongodb.net/database
    restart: always
